export const translations = {
  ar: {
    nav: {
      collections: "المجموعات",
      bags: "الحقائب",
      watches: "الساعات",
      jewelry: "المجوهرات",
      eyewear: "النظارات",
      about: "عن سولن",
      language: "EN",
    },
    hero: {
      tagline: "حيث تلتقي الرقة بالأبدية",
      title: "SOLEN",
      subtitle: "مجموعة صيف ٢٠٢٥",
      cta: "اكتشف المجموعة",
      scroll: "تصفح",
    },
    marquee: "إكسسوارات فاخرة · حقائب · ساعات · مجوهرات · نظارات · SOLEN · ",
    categories: {
      title: "المجموعات",
      subtitle: "أربع عوالم من الأناقة الخالدة",
      items: [
        { name: "الحقائب", name_en: "BAGS", count: "٢٤ قطعة" },
        { name: "الساعات", name_en: "WATCHES", count: "١٨ قطعة" },
        { name: "المجوهرات", name_en: "JEWELRY", count: "٣٢ قطعة" },
        { name: "النظارات", name_en: "EYEWEAR", count: "١٢ قطعة" },
      ],
    },
    featured: {
      title: "المختارات",
      subtitle: "قطع استثنائية من قلب مجموعتنا",
      cta: "عرض التفاصيل",
      badge: "جديد",
    },
    editorial: {
      title: "فن الأناقة",
      body: "في سولن، نؤمن بأن كل قطعة تحكي قصة. قصة الحِرفية الراقية، والتصميم الذي يتجاوز الزمن، والمواد التي تُختار بعناية من أرقى بقاع العالم.",
      cta: "اقرأ المزيد",
    },
    newsletter: {
      title: "انضم إلى عالم سولن",
      subtitle: "كن أول من يعلم بمجموعاتنا الجديدة والعروض الحصرية",
      placeholder: "بريدك الإلكتروني",
      cta: "اشترك",
    },
    footer: {
      tagline: "الأناقة بلا حدود",
      links: ["سياسة الخصوصية", "الشروط والأحكام", "تواصل معنا", "المتاجر"],
      rights: "© ٢٠٢٥ سولن. جميع الحقوق محفوظة.",
    },
  },
  en: {
    nav: {
      collections: "Collections",
      bags: "Bags",
      watches: "Watches",
      jewelry: "Jewelry",
      eyewear: "Eyewear",
      about: "About",
      language: "عربي",
    },
    hero: {
      tagline: "Where Elegance Meets Eternity",
      title: "SOLEN",
      subtitle: "Summer Collection 2025",
      cta: "Discover the Collection",
      scroll: "Scroll",
    },
    marquee: "Luxury Accessories · Bags · Watches · Jewelry · Eyewear · SOLEN · ",
    categories: {
      title: "Collections",
      subtitle: "Four worlds of timeless elegance",
      items: [
        { name: "Bags", name_en: "BAGS", count: "24 Pieces" },
        { name: "Watches", name_en: "WATCHES", count: "18 Pieces" },
        { name: "Jewelry", name_en: "JEWELRY", count: "32 Pieces" },
        { name: "Eyewear", name_en: "EYEWEAR", count: "12 Pieces" },
      ],
    },
    featured: {
      title: "Curated Selections",
      subtitle: "Exceptional pieces from the heart of our collection",
      cta: "View Details",
      badge: "New",
    },
    editorial: {
      title: "The Art of Elegance",
      body: "At SOLEN, we believe every piece tells a story. A story of masterful craftsmanship, timeless design, and materials sourced from the finest corners of the world.",
      cta: "Read More",
    },
    newsletter: {
      title: "Join the World of SOLEN",
      subtitle: "Be the first to know about our new collections and exclusive offers",
      placeholder: "Your email address",
      cta: "Subscribe",
    },
    footer: {
      tagline: "Elegance Without Limits",
      links: ["Privacy Policy", "Terms & Conditions", "Contact Us", "Stores"],
      rights: "© 2025 SOLEN. All rights reserved.",
    },
  },
};

export const products = [
  {
    id: 1,
    name_ar: "حقيبة لونا الذهبية",
    name_en: "Luna Gold Bag",
    category: "bags",
    price: "٧٥ د.ك",
    price_en: "KWD 75",
    isNew: true,
    color: "#c9a96e",
    gradient: "from-amber-100 to-yellow-50",
  },
  {
    id: 2,
    name_ar: "ساعة إيكو الكلاسيكية",
    name_en: "Echo Classic Watch",
    category: "watches",
    price: "١٢٠ د.ك",
    price_en: "KWD 120",
    isNew: false,
    color: "#a07840",
    gradient: "from-stone-100 to-amber-50",
  },
  {
    id: 3,
    name_ar: "قلادة أورا الذهبية",
    name_en: "Aura Gold Necklace",
    category: "jewelry",
    price: "٣٥ د.ك",
    price_en: "KWD 35",
    isNew: true,
    color: "#e8c99a",
    gradient: "from-yellow-50 to-amber-100",
  },
  {
    id: 4,
    name_ar: "نظارة سيلين الشمسية",
    name_en: "Celine Sunglasses",
    category: "eyewear",
    price: "٢٨ د.ك",
    price_en: "KWD 28",
    isNew: false,
    color: "#1a1a1a",
    gradient: "from-stone-200 to-gray-100",
  },
  {
    id: 5,
    name_ar: "حقيبة نوفا الكريمية",
    name_en: "Nova Cream Bag",
    category: "bags",
    price: "٨٥ د.ك",
    price_en: "KWD 85",
    isNew: true,
    color: "#f5f0e8",
    gradient: "from-amber-50 to-stone-100",
  },
  {
    id: 6,
    name_ar: "خاتم سولار الذهبي",
    name_en: "Solar Gold Ring",
    category: "jewelry",
    price: "١٨ د.ك",
    price_en: "KWD 18",
    isNew: false,
    color: "#c9a96e",
    gradient: "from-yellow-100 to-amber-50",
  },
];
